const SensorsCapabilities = {
        'Temperature':      { caption: 'Temperature',           capability: 'measure_temperature.{sensor}',                 units: { default: 'C',          units_field: 'TempUnit',            units_template: '°{value}' } },
        'Humidity':         { caption: 'Humidity',              capability: 'measure_humidity.{sensor}',                    units: { default: '%',          units_field: null,                  units_template: '{value}' } },       
        'DewPoint':         { caption: 'Dew point',             capability: 'measure_temperature.dew_point.{sensor}',       units: { default: 'C',          units_field: 'TempUnit',            units_template: '°{value}' } },
        'Pressure':         { caption: 'Pressure',              capability: 'measure_pressure.{sensor}',                    units: { default: 'hPa',        units_field: 'PressureUnit',        units_template: '{value}' } },
        'CarbonDioxide':    { caption: 'Carbon dioxide',        capability: 'measure_co2.{sensor}',                         units: { default: 'ppm',        units_field: null,                  units_template: '{value}' } },   
        'Illuminance':      { caption: 'Illuminance',           capability: 'measure_luminance.{sensor}',                   units: { default: 'lx',         units_field: null,                  units_template: '{value}' } },     
        'CF1':              { caption: 'CF1',                   capability: 'measure_particulate_matter.cf1.{sensor}',      units: { default: 'µg/m³',      units_field: null,                  units_template: '{value}' } },
        'CF2.5':            { caption: 'CF2.5',                 capability: 'measure_particulate_matter.cf2_5.{sensor}',    units: { default: 'µg/m³',      units_field: null,                  units_template: '{value}' } },
        'CF10':             { caption: 'CF10',                  capability: 'measure_particulate_matter.cf10.{sensor}',     units: { default: 'µg/m³',      units_field: null,                  units_template: '{value}' } },
        'PM1':              { caption: 'PM1',                   capability: 'measure_particulate_matter.pm1.{sensor}',      units: { default: 'ppd',        units_field: null,                  units_template: '{value}' } },
        'PM2.5':            { caption: 'PM2.5',                 capability: 'measure_particulate_matter.pm2_5.{sensor}',    units: { default: 'ppd',        units_field: null,                  units_template: '{value}' } },
        'PM10':             { caption: 'PM10',                  capability: 'measure_particulate_matter.pm10.{sensor}',     units: { default: 'ppd',        units_field: null,                  units_template: '{value}' } },
        'PB0.3':            { caption: 'PB0.3',                 capability: 'measure_particulate_matter.pb0_3.{sensor}',    units: { default: 'ppd',        units_field: null,                  units_template: '{value}' } },
        'PB0.5':            { caption: 'PB0.5',                 capability: 'measure_particulate_matter.pb0_5.{sensor}',    units: { default: 'ppd',        units_field: null,                  units_template: '{value}' } },
        'PB1':              { caption: 'PB1',                   capability: 'measure_particulate_matter.pb1.{sensor}',      units: { default: 'ppd',        units_field: null,                  units_template: '{value}' } },
        'PB2.5':            { caption: 'PB2.5',                 capability: 'measure_particulate_matter.pb2_5.{sensor}',    units: { default: 'ppd',        units_field: null,                  units_template: '{value}' } },
        'PB5':              { caption: 'PB5',                   capability: 'measure_particulate_matter.pb5.{sensor}',      units: { default: 'ppd',        units_field: null,                  units_template: '{value}' } },
        'PB10':             { caption: 'PB10',                  capability: 'measure_particulate_matter.pb10.{sensor}',     units: { default: 'ppd',        units_field: null,                  units_template: '{value}' } },
        'UvLevel':          { caption: 'UV index',              capability: 'measure_ultraviolet.{sensor}',                 units: { default: '',           units_field: null,                  units_template: '{value}' } },
        'Frequency':        { caption: 'Frequency',             capability: 'measure_frequency.{sensor}',                   units: { default: 'Hz',         units_field: null,                  units_template: '{value}' } },
        'Voltage':          { caption: 'Voltage',               capability: 'measure_voltage.{sensor}',                     units: { default: 'V',          units_field: null,                  units_template: '{value}' } },
        'Current':          { caption: 'Current',               capability: 'measure_current.{sensor}',                     units: { default: 'A',          units_field: null,                  units_template: '{value}' } },
        'Power':            { caption: 'Power',                 capability: 'measure_power.{sensor}',                       units: { default: 'W',          units_field: null,                  units_template: '{value}' } },
        'Factor':           { caption: 'Power factor',          capability: 'measure_power_factor.{sensor}',                units: { default: '',           units_field: null,                  units_template: '{value}' } },
        'ApparentPower':    { caption: 'Apparent power',        capability: 'measure_apparent_power.{sensor}',              units: { default: 'VA',         units_field: null,                  units_template: '{value}' } },
        'ReactivePower':    { caption: 'Reactive power',        capability: 'measure_power_reactive.{sensor}',              units: { default: 'VAr',        units_field: null,                  units_template: '{value}' } },
        'Total':            { caption: 'Power meter',           capability: 'meter_power.{sensor}',                         units: { default: 'kWh',        units_field: null,                  units_template: '{value}' } },
        'Today':            { caption: 'Power meter today',     capability: 'meter_energy_today.{sensor}',                  units: { default: 'kWh',        units_field: null,                  units_template: '{value}' } },
        'Yesterday':        { caption: 'Power meter yesterday', capability: 'meter_energy_yesterday.{sensor}',              units: { default: 'kWh',        units_field: null,                  units_template: '{value}' } },
    };

module.exports.SensorsCapabilities = SensorsCapabilities;
